### PR TITLE
fix: Breakpoint expiry now uses create time

### LINKED ISSUE #66: Breakpoint expiry not working as expected when talking to Firebase Backend
The internals of the Java Agent are looking for a 'createTime' field when computing the expiration time for breakpoints. In Snapshot Debugger mode (talking to a Firebase backend), the field is actually called 'createTimeUnixMsec', and has a different format. As a result the agent simply uses the current time as the create time.

### PR DESCRIPTION
**Pull request by jasonborg**
Updated the internal agent code and the breakpoint json model to support the `createTimeUnixMsec` field. This field is used in the Firebase Backend version of the agent to represent the breakpoint creation time. When determining the breakpoint expiry this field will now be used if present.

Fixes #66

### CODE REVIEW

File: src/agent/model_util.h [hunk 1]
```diff
@@ -670,6 +675,12 @@ inline bool operator!= (const TimestampModel& t1, const TimestampModel& t2) {
   return !(t1 == t2);
 }
 
+inline TimestampModel GetCreateTimestamp(const BreakpointModel& model) {
+  return (model.create_time != kUnspecifiedTimestamp)
+             ? model.create_time
+             : model.create_time_unix_msec;
+}
+
```
Comment (mctavish) [inline src/agent/model_util.h:683]: Nit: I always find helper methods like this to be a bit frustrating; it's non-obvious as to where the implementation is when viewing it from where it is used (ie. jvm_breakpoint.cc).  I'd prefer that this either be part of the BreakpointModel or in the jvm_breakpoint file, but accept that this is just personal preference.

**Review by mctavish — APPROVED** [review]

File: src/agent/model_util.h (hunk 1 above)
Comment (jasonborg) [reply src/agent/model_util.h:685]: I initially wanted to put it in the BreakpointModel, the issue with that was kUnspecifiedTimestamp and the TimestampModel comparison operators are defined here in model_util. To help, I've introduced a model_util namespace to wrap this helper method.
